name: Deploy to Server
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [ deploy-to-server ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_PRODUCTION_IP }}
          username: ${{ secrets.DEPLOY_PRODUCTION_USER }}
          port: 22
          key: ${{ secrets.DEPLOY_PRODUCTION_SSH_KEY }}
          passphrase: ${{ secrets.DEPLOY_PRODUCTION_SSH_KEY_PASSPHRASE }}
          source: "wwwroot/*"
          target: /var/www/html/